//
// Generated file, do not edit! Created by opp_msgtool 6.4 from AKEMessage.msg.
//

#ifndef __AKEMESSAGE_M_H
#define __AKEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AKEMessage;
/**
 * Enum generated from <tt>AKEMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * enum MessageType
 * {
 *     M1_MSG = 1;
 *     M2_MSG = 2;
 *     M3_MSG = 3;
 *     M4_MSG = 4;
 * }
 * </pre>
 */
enum MessageType {
    M1_MSG = 1,
    M2_MSG = 2,
    M3_MSG = 3,
    M4_MSG = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageType& e) { int n; b->unpack(n); e = static_cast<MessageType>(n); }

/**
 * Class generated from <tt>AKEMessage.msg:8</tt> by opp_msgtool.
 * <pre>
 * packet AKEMessage
 * {
 *     int type \@enum(MessageType);
 *     int payloadBytes;   // Lưu kích thước phần mật mã thô (Kyber PK, CT, ...)
 *     int overheadBytes;  // Lưu kích thước phần rác/định dạng (TLS Header, Extension, ...)
 * }
 * </pre>
 */
class AKEMessage : public ::omnetpp::cPacket
{
  protected:
    int type = 0;
    int payloadBytes = 0;
    int overheadBytes = 0;

  private:
    void copy(const AKEMessage& other);

  protected:
    bool operator==(const AKEMessage&) = delete;

  public:
    AKEMessage(const char *name=nullptr, short kind=0);
    AKEMessage(const AKEMessage& other);
    virtual ~AKEMessage();
    AKEMessage& operator=(const AKEMessage& other);
    virtual AKEMessage *dup() const override {return new AKEMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getPayloadBytes() const;
    virtual void setPayloadBytes(int payloadBytes);

    virtual int getOverheadBytes() const;
    virtual void setOverheadBytes(int overheadBytes);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AKEMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AKEMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AKEMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<AKEMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __AKEMESSAGE_M_H

